import ThemeRegistry from '@/components/ThemeRegistry/ThemeRegistry'
import './globals.css'
import { Inter } from 'next/font/google'
import { Typography, Box, Stack } from '@mui/material';
import Footer from '@/components/footer';

import NavBar from '@/components/navbar';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Warm Wave Studio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel='icon' href='/favicon.ico' />
      </head>
      <body className={inter.className}>
        <ThemeRegistry>
          <NavBar />
          <main>{children}</main>
          <Footer />
        </ThemeRegistry>
      </body>
    </html>
  )
}
